# Generated by Django 2.2.4 on 2021-04-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullCRUDapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='creator',
            new_name='party_master',
        ),
    ]
