# Generated by Django 2.2.4 on 2021-03-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='favorite_toy',
        ),
    ]
