# Generated by Django 2.2.4 on 2021-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='num_of_legs',
            field=models.IntegerField(default=4),
        ),
    ]
