# Generated by Django 2.2.4 on 2021-03-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='leash_length',
            field=models.IntegerField(null=True),
        ),
    ]
